services:
  app:
    build:
      dockerfile: ./docker/bot.dockerfile
    container_name: dislate
    networks:
      - dislate
    ports:
      - 8080:8080
    env_file: .env

  libretranslate:
    image: libretranslate/libretranslate
    container_name: dislate-libretranslate
    networks:
      - dislate
    ports:
      - "5000:5000"
    tty: true
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']

  translateer:
    build:
      dockerfile: ./docker/translateer.dockerfile
    container_name: dislate-translateer
    networks:
      - dislate
    ports:
      - "8999:8999"
    environment:
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000/?--user-data-dir=./tmp/translateer-data"
      PAGE_COUNT: "5"
    depends_on:
      - browserless

  browserless:
    image: browserless/chrome
    container_name: dislate-translateer-browserless
    restart: always
    networks:
      - dislate
    environment:
      CONNECTION_TIMEOUT: "-1"

networks:
  dislate:
    driver: bridge
