services:
  app:
    build:
      dockerfile: ./dockerfile
    container_name: dislate
    networks:
      - dislate
    ports:
      - 8080:8080
    env_file: .env

networks:
  dislate:
    driver: bridge
volumes:
  db-data:
